### ISSUE TITLE
Does not install in v11

### ISSUE THREAD

**Issue by MotoMoto1234** [mclemente/fvtt-condition-lab-triggler#1]
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/116308065/bd2ba710-a0e9-4bcf-9bb0-a9bbe0c384f9)

**Comment by mclemente** [comment]
I got the link wrong (`/condition-lab-triggler/` instead of `/fvtt-condition-lab-triggler/`). It should work now.

**Comment by MotoMoto1234** [comment]
This is fixed, its installable just fine now
