### ISSUE TITLE
Module Conflict w/ Status Halo - CLT doesn't behave the same as CUB did.

### ISSUE THREAD

**Issue by tjlanza** [mclemente/fvtt-condition-lab-triggler#10]
**Describe the bug**
Under v10.303, the predecessor module, [Combat Utility Belt](https://github.com/death-save/combat-utility-belt) v1.10.4 was compatible with [Status Halo](https://gitlab.com/mxzf/status-halo) v0.1.1 but under v11.305, CLT v1.4.1 does not play nicely.

**To Reproduce**
Install both modules.

**Expected behavior**
Status Halo's icon placement should override CLT's.

**Screenshots**
v10 & CUB
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/21128724/525f592d-071d-4098-bb5d-5703eedeb1f5)

v11 & CLT - You can see that the reorganization doesn't take place fully, but parts of it do. There's a visible offset in the icon placement.
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/21128724/8f4f5791-5359-4c62-af28-93ee8c5f4d97)

libWrapper identifies there's a potential conflict, but nothing actually appears in the console that corresponds.
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/21128724/a0e8c0d9-292a-432d-88a0-acd246d48849)

**Environment Info (please complete the following information):**
 - Foundry Version: v10.303 w/ CUB, v11.305 w/ CLT
 - Game System / Version: Shadowrun 5 v0.11.2 in both
 - Browser: Chrome
 - OS: Windows 10

**Additional context**

**Comment by mclemente** [comment]
It's Status Halo that is breaking this. Any module/system that directly wraps a method will conflict with libWrapper.

It worked with CUB because it overwrote `Token.prototype._refreshEffects` and then Status Halo was able to call it.

The best I can do is to make it so the icon size setting has no effect if the Status Halo is enabled.
