### ISSUE TITLE
Can't edit Active Effect in v11 3.5e system

### ISSUE THREAD

**Issue by Oryan77** [mclemente/fvtt-condition-lab-triggler#11]
**Describe the bug**
I apologize if this is a system restriction and not a bug, but I was wondering if it should be possible to edit Active Effects in the 3.5e system via the Condition Lab now that v11 is out? 

There is no Effect Description editing controls within the Active Effect option in Condition Lab, but the controls do exist when editing an Active Effect via the DFreds Effect Panel module (double clicking on the active condition icon). The issue is that the Active Effect description doesn't save after ending the effect because it is not editing the default Active Effect for the condition/buff.

Is this something that Condition Lab could do or does the 3.5e system need to provide access to this feature?

![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/49130820/d57bcf33-fdba-422e-ad93-305890fd2da9)

 - Foundry Version: [v.11.307]
 - Game System / Version: [3.5e v2.3.2]
 - CUB Version [1.4.1]
 - Browser [chrome, safari]
 - OS [Windows 10]

**Comment by TheNittles** [comment]
I'm having this same issue in the D&D 4th edition system, too!
