### ISSUE TITLE
Invisible Condition added does not make creatures invisible in Foundry VTT

### ISSUE THREAD

**Issue by etoy22** [mclemente/fvtt-condition-lab-triggler#13]
Using the Invisible Condition added by fvtt-condition-lab-triggler does not make creatures invisible in Foundry VTT.

**Comment by mclemente** [comment]
Does this issue persists on v1.4.3? It doesn't "hide" the token (e.g. it doesn't become transparent, but it should becomes blue-tinted and is invisible to other tokens.

https://github.com/mclemente/fvtt-condition-lab-triggler/assets/5288872/7170e461-2878-46d4-9bb0-36c620f81e0c

**Comment by etoy22** [comment]
The issue doesn't persist at this point.
