### ISSUE TITLE
Macro arguments

### ISSUE THREAD

**Issue by SuperMalakan** [mclemente/fvtt-condition-lab-triggler#16]
Hey!

CUB executed macros used to allow `args[0]`, for example. This fails with CLT 1.4.1 in Foundry 11.311, `args` is not defined.

Would it be possible to get some documentation for what can be done in the CLT executed macros please?

**Comment by mclemente** [comment]
Have you recently updated from Foundry V10? Because the args change is a Foundry thing, not an actual CLT change.

**Comment by SuperMalakan** [comment]
That would be the cause. Sorry, my mistake!
