### ISSUE TITLE
Active Effect Descriptions not carrying over to applied Conditions

### ISSUE THREAD

**Issue by TheNittles** [mclemente/fvtt-condition-lab-triggler#18]
**Describe the bug**
Now that we can edit the Description Field of the Active Effects, I went and added mechanical effects to all my effect descriptions via Condition Lab. When I apply these conditions to an actor, the instance of that condition applied to the actor has a blank Description Field. This prevents me from using modules like Visual Active Effects or Combat Carousel to have the rules text of conditions at a glance.

**To Reproduce**
1) Add a description to a condition's active effect via Condition Lab.
2) Apply that condition to an actor via the Token UI
3) View the condition on the actor. I usual Visual Active Effects and Combat Carousel, but you can also open the effect in the actor's character sheet.
4) The effect's name, attributes, duration, etc, are all set correctly. The description field, however, is blank.

**Expected behavior**
The description field should have the text entered into the effect via Condition Lab.

**Screenshots**
In Condition Lab, I've added a description of Prone to its Active Effect
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/137443034/0937826c-f697-40ff-9cf6-4a4f0e19ff66)

After adding Prone to the Skelly actor via the Token UI, the Description Field is blank both when viewed via Visual Active Effects and by opening the effect from the actor's character sheet.
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/137443034/c8b00837-28e1-4924-838d-67080740e891)

**Environment Info (please complete the following information):**
 - Foundry Version: v11 Stable, Build 313
 - Game System / Version: dnd4e v0.4.25
 - CUB Version: Condition Lab and Triggler v1.4.3
 - Browser: Chrome
 - OS: Windows 11

**Additional context**
This is definitely the Custom version of Prone added by Condition Lab, because that icon is not the standard Prone icon for this system. I didn't show it, but Attributes of any Active Effects are properly carrying over and applying to Actors. It's only the Description that is getting lost.

**Comment by mclemente** [comment]
Should be fixed now.
