### ISSUE TITLE
Error occurs in Dnd5e 3.0.0

### ISSUE THREAD

**Issue by strongpauly** [mclemente/fvtt-condition-lab-triggler#26]
**Describe the bug**
When applying a condition created by Condition Lab & Triggler, an error is logged in the console, and the condition is not applied

**To Reproduce**
1. Configure "System - Default" mapping type in the Condition Lab
2. Select a token
3. Apply one of the conditions added by Condition Lab & Triggler
4. See error:
```
commons.js:3894 Uncaught (in promise) Error: undefined. ActiveEffect5e [dnd5econdition-l] validation errors:
  _id: must be a valid 16-character alphanumeric ID
[Detected 1 package: system:dnd5e]
    at DataModelValidationFailure.asError (commons.js:3894:14)
    at ActiveEffect5e.validate (commons.js:7164:61)
    at new DataModel (commons.js:6918:12)
    at new Document (commons.js:7583:3)
    at new BaseActiveEffect (commons.js:8914:3)
    at new ClientDocumentMixin (foundry.js:13979:7)
    at new ActiveEffect (foundry.js:17730:1)
    at new ActiveEffect5e (active-effect.mjs:8:16)
    at ActiveEffect5e.fromStatusEffect (active-effect.mjs:62:12)
    at TokenDocument5e.toggleActiveEffect (token.mjs:108:32)
    at Token5e.toggleEffect (foundry.js:55799:44)
    at TokenHUD._onToggleEffect (foundry.js:82713:24)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Expected behavior**
Condition should be applied correctly

**Environment Info (please complete the following information):**
 - Foundry Version: v11 315
 - Game System / Version: dnd5e 3.0.0
 - CUB Version: 1.4.12
 - Browser: Electron
 - OS: Mac OSX

**Comment by mclemente** [comment]
I'm gonna be honest, the fix to this error is simple, but the update broke way more stuff. For example, Triggler is completely broken due to the move to data models.

I'll take the opportunity to give the module a proper rewrite. Don't expect an update any time soon.

**Comment by Vishara** [comment]
Is it possible that you can create a small fix for the condition to be applied correctly, even when the triggers dont work?
I dont play with Triggers, but with many custom Conditions which are currently the only reason why I cannot play in v3. 

Or if you dont want to update a new "workaround" version, can you give the information, what has to be changed in the files, if this is easy?

I whould really appriciate this :D
Greetings Visha

**Comment by mclemente** [comment]
The issue with Triggler should've been fixed with release 1.5.0, but I'm keeping this issue open for a bit in case any other errors show up.

**Comment by cs96and** [comment]
Is v1.5.0 compatible with both dnd5e v2.4.1 and v3.0.0?

**Comment by mclemente** [comment]
> Is v1.5.0 compatible with both dnd5e v2.4.1 and v3.0.0?

Yes, it should be compatible with both versions.
