### ISSUE TITLE
Canvas error reported after logging in.

### ISSUE THREAD

**Issue by farling42** [mclemente/fvtt-condition-lab-triggler#3]
Errors is reported immediately on logging in:

![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/17485384/efc2a6e2-8059-46c0-a6b4-241460867ff1)
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/17485384/49d1e414-df59-4156-b144-c311b47237d9)
![image](https://github.com/mclemente/fvtt-condition-lab-triggler/assets/17485384/de2d0e4a-7d19-4b49-af9e-9fb01d42c871)

**Comment by farling42** [comment]
The value of `effectSize` is `CLT.SETTINGS.TokenUtility.TokenEffectSize.choices.small`

**Comment by farling42** [comment]
No error in version 1.2 :-)

**Comment by mclemente** [comment]
Yes, I've added a wrong default setting, so the wrapper that read that value screwed the map loading.
