### ISSUE TITLE
Sync "Health Estimate" "Death state on Condition" not working when not in combat.

### ISSUE THREAD

**Issue by Weskernation** [mclemente/fvtt-condition-lab-triggler#48]
**Describe the bug**
sync with Module "Health Estimate" "Death state on Condition" not working when not in combat.
During combat, the moment you put the "Dead" condition on the token. it's state goes to dead (instead of unconscious). This works as it should work.
However when you are not in combat giving the token the dead condition. their state from Health estimate stays at  e.g. Unharmed

**To Reproduce**
Condition-lab-triggler + Health estimate active
1. Go to 'a token' when not in combat state.
2. Hover over a token and you can see their health state from Health Estimate
3. Right-Click on 'a token' and add the Dead condition. The token's health state is unchanged while it should go to Dead (defeated)
4. To compare: Repeat when combat state is on. and all works as intended

**Environment Info (please complete the following information):**
 - Foundry Version: 3.1.5
 - Game System / Version: [e.g. dnd5e 3.1.1 - 3.1.2]
 - CUB Version [not used anymore, replaced by [condition-lab-triggler]
 - OS [e.g. Windows 11]

**Additional context**
When condition-lab-triggler is turned off. in-and-out of combat, the "Death state on Condition" works

**Comment by mclemente** [comment]
This might be a bug on Health Estimate's side actually (I'm the dev of both modules). You should've been able to see the "Death Marker" setting on HE's "Behavior Settings" menu if you have CLT enabled.

Investigating this issue I've noticed it was not actually available.
If it were working properly, you should change that setting to the image path you've chosen instead.
I'll release a new version of Health Estimate, so test with it and let me know if that fixed it for you.

**Comment by Weskernation** [comment]
**"If it were working properly, you should change that setting to the image path you've chosen instead."**
The death marker is the standard foundry one. not an added one in CLT. (add a death state in CLT does not fix it either).

The moment CLT is disabled, giving a token the dead condition makes it dead. (but then of course we're missing the conditions we added through CLT)

**"You should've been able to see the "Death Marker" setting on HE's "Behavior Settings" menu if you have CLT enabled."**
The option to check and name it is indeed visible. (always been visible)

**Comment by Weskernation** [comment]
@mclemente The 31.8.7 update for Health Estimate **semi** fixed it. Now we have to put in a custom condition. If we do not can/want to add a custom condition. can it work on the standard foundry condition?

<img width="519" alt="image" src="https://github.com/mclemente/fvtt-condition-lab-triggler/assets/119079571/2f95c077-4558-472d-8645-2e2c518a2c2b">



When empty make it work on the Default Foundry Dead token <img width="87" alt="image" src="https://github.com/mclemente/fvtt-condition-lab-triggler/assets/119079571/1e059c8d-428f-4462-b840-54cd55b8b664">

**Comment by mclemente** [comment]
> CLT Deactivated and Dead Condition **IN** and **OUT**side of combat: <img alt="image" width="513" src="https://private-user-images.githubusercontent.com/119079571/322434837-a12724b2-8096-4734-a043-5662bdec7427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTkwMDYsIm5iZiI6MTcxMzE5ODcwNiwicGF0aCI6Ii8xMTkwNzk1NzEvMzIyNDM0ODM3LWExMjcyNGIyLTgwOTYtNDczNC1hMDQzLTU2NjJiZGVjNzQyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNjMxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTJlMTllOWVhMzgxZjE3ZjVlNWY1YjNlYjYzZTEyY2EwNGZmYjM0MmJmM2JhNDg5ZDUxNzk1MmFkYzk5YzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PRjFevBunsZi8f8xhcUfnwpqRobSQt2ux1AjSsC_i1o">

Can you test this with just the two modules enabled, probably on a brand new world? The "defeated" overlay on dnd5e *isn't* the new skull.
If you're not changing the icon, the setting should be set to the default ("systems/dnd5e/icons/svg/statuses/dead.svg").

**Comment by Weskernation** [comment]
On a new world with only HEstimate + CLT activated. When clicked on Reset Defaults the "Death state on Conditions" is turned off. and the Death Marker changed into ("systems/dnd5e/icons/svg/statuses/dead.svg"). We just need to enable the "Death state on Conditions" then it works.
<img width="531" alt="image" src="https://github.com/mclemente/fvtt-condition-lab-triggler/assets/119079571/76483e38-0802-4e30-b0a7-f026b4abaf53">

**Comment by mclemente** [comment]
> The "defeated" overlay on dnd5e _**is**_ the new skull.

Uh, how odd, on my test world on latest dnd5e it still is the original skull, and there's nothing on the system or the module that changes that.

Anyway, thank you for checking out the settings, it didn't occur to me you could have changed them /facepalm
